const DATA = [
  {
    section: "Section 9.11",
    description: "ArrayList methods — size(), get(), add(), remove(), clear(), and isEmpty(). Watch out for the difference between remove(int index) and remove(Object value).",
    title: "Section 9.11 — ArrayList",
    questions: [
      { q: "`itemList().size` returns 8.", choices: ["True","False"], answer: 1, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(0); itemList.add(0); itemList.add(0); itemList.add(0);\nitemList.add(99); itemList.add(98); itemList.add(97); itemList.add(96);", explanation: "itemList() is calling a method that doesn't exist — it should be itemList.size() with a dot. Also, size() needs parentheses, not just .size." },
      { q: "`itemList.size(8)` returns 8.", choices: ["True","False"], answer: 1, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(0); itemList.add(0); itemList.add(0); itemList.add(0);\nitemList.add(99); itemList.add(98); itemList.add(97); itemList.add(96);", explanation: "size() counts how many items are in the list — it takes no arguments. You can't pass 8 to it!" },
      { q: "`itemList.size()` returns 8.", choices: ["True","False"], answer: 0, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(0); itemList.add(0); itemList.add(0); itemList.add(0);\nitemList.add(99); itemList.add(98); itemList.add(97); itemList.add(96);", explanation: "Eight items were added to the list, so size() returns 8. It's just counting — 8 items in, 8 comes out!" },
      { q: "`itemList.get(8)` returns 96.", choices: ["True","False"], answer: 1, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(0); itemList.add(0); itemList.add(0); itemList.add(0);\nitemList.add(99); itemList.add(98); itemList.add(97); itemList.add(96);", explanation: "Lists count from 0, so 8 items fill spots 0 through 7. Asking for spot 8 would crash — it doesn't exist!" },
      { q: "`itemList.isEmpty()` removes all elements.", choices: ["True","False"], answer: 1, code: "", explanation: "isEmpty() only checks if the list has no items — it just answers yes or no. To actually remove everything, use clear()." },
      { q: "After `itemList.clear()`, `itemList.get(0)` is an invalid access.", choices: ["True","False"], answer: 0, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(0); itemList.add(0); itemList.add(0); itemList.add(0);\nitemList.add(99); itemList.add(98); itemList.add(97); itemList.add(96);\nitemList.clear(); // empties the list — size is now 0", explanation: "clear() removes everything, leaving the list empty. Calling get(0) on an empty list crashes the program." },
      { q: "`itemList.get(1)` returns 77.", choices: ["True","False"], answer: 0, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(33); itemList.add(77); itemList.add(44);", explanation: "The list is [33, 77, 44]. Spot 0 is 33, spot 1 is 77. So get(1) = 77 — correct!" },
      { q: "`itemList.add(1, 55)` changes itemList to: 33 55 77 44.", choices: ["True","False"], answer: 0, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(33); itemList.add(77); itemList.add(44);\n// itemList is currently: [33, 77, 44]\nitemList.add(1, 55); // inserts 55 at index 1", explanation: "Inserting 55 at spot 1 pushes 77 and 44 to the right, making [33, 55, 77, 44]. That matches the claim!" },
      { q: "`itemList.add(0, 99)` inserts 99 at the front of the list.", choices: ["True","False"], answer: 0, code: "ArrayList<Integer> itemList = new ArrayList<Integer>();\nitemList.add(33); itemList.add(77); itemList.add(44);\n// itemList is currently: [33, 77, 44]\nitemList.add(0, 99); // inserts 99 at index 0 (front)", explanation: "Spot 0 is the very beginning of the list. Inserting at spot 0 pushes everything else over, so 99 goes right at the front." },
      { q: "Assuming itemList is 99 33 55 77 44, then `itemList.remove(55)` results in: 99 33 77 44", choices: ["True","False"], answer: 1, code: "", explanation: "On an ArrayList<Integer>, remove(55) removes the item at INDEX 55 — not the value 55. There's no index 55 in a 5-item list, so it throws an exception!" },
      { q: "To maintain a list in ascending sorted order, a given new item should be inserted at the position of the first element that is greater than the item.", choices: ["True","False"], answer: 0, code: "", explanation: "To keep a list sorted low-to-high, put the new item just before the first one that is bigger than it. That keeps the order correct." },
      { q: "To maintain a list in descending sorted order, a given new item should be inserted at the position of the first element that is equal to the item.", choices: ["True","False"], answer: 1, code: "", explanation: "In a high-to-low list, you insert before the first item that is SMALLER than the new one, not equal to it." },
    ]
  },
  {
    section: "Section 12.2",
    title: "Section 12.2",
    questions: []
  },
  {
    section: "Section 15.1",
    description: "System.out and System.in — how Java's standard streams work, buffering behavior, the role of PrintStream, InputStream, and how Scanner wraps an InputStream.",
    title: "Section 15.1 — Output and Input Streams",
    questions: [
      { q: "Characters written to `System.out` are immediately written to a system's standard output.", choices: ["True","False"], answer: 1, code: "", explanation: "System.out stores output in a buffer (like a waiting room). Characters wait there and aren't sent out right away." },
      { q: "To use `System.out`, a program must include the statement `import java.io.PrintStream;`", choices: ["True","False"], answer: 1, code: "import java.io.PrintStream;", explanation: "System.out is part of java.lang, which Java loads automatically for every program. You never need to import it." },
      { q: "Various standard data types are converted to a character sequence by `print()` and `println()`.", choices: ["True","False"], answer: 0, code: "", explanation: "That's the whole point of print() and println()! They convert ints, doubles, booleans — everything — into readable text." },
      { q: "`System.in` is a predefined InputStream associated with the system's standard input.", choices: ["True","False"], answer: 0, code: "", explanation: "System.in IS the standard input stream — it's always there, ready to read keyboard input." },
      { q: "A program must import the `InputStream` class in order to use `System.in`.", choices: ["True","False"], answer: 1, code: "", explanation: "System.in is in java.lang, which is automatically loaded. No import needed to use it." },
      { q: "A read from `System.in` will read bytes from a buffer filled by the operating system.", choices: ["True","False"], answer: 0, code: "", explanation: "When you type at the keyboard, the OS collects what you type in a buffer. System.in then reads from that buffer." },
      { q: "The throws clause for using an InputStream is `throws InputException`.", choices: ["True","False"], answer: 1, code: "throws InputException", explanation: "The correct clause is 'throws IOException' — InputException doesn't exist in Java!" },
      { q: "What class has methods to extract strings, integers, and other types from an InputStream?", choices: ["Scanner","System.in","IOException","BufferedReader","FileReader"], answer: 0, code: "", explanation: "Scanner is the toolbox that unpacks streams into usable types like String, int, and double using methods like nextInt() and nextLine()." },
      { q: "What is passed to the `Scanner`'s constructor to initialize a Scanner object?", choices: ["System.in","An InputStream","nextInt()","A String filename","A FileOutputStream"], answer: 1, code: "", explanation: "Scanner's constructor takes any InputStream — and System.in is just one example of an InputStream you can wrap with Scanner." },
    ]
  },
  {
    section: "Section 15.2",
    description: "printf() format specifiers — %d, %s, %f, %%, width/precision flags, and how buffering determines when output actually appears on screen.",
    title: "Section 15.2 — printf()",
    questions: [
      { q: "What is output to the screen?", choices: ["%d - %s","age - name","20 - Alice","Alice - 20","20.0 - Alice"], answer: 2, code: "String name = \"Alice\";\ndouble gpa = 3.5;\nint age = 20;\nSystem.out.printf(\"%d - %s\", age, name);", explanation: "%d grabs the int (age = 20) and %s grabs the String (name = 'Alice'), giving '20 - Alice'." },
      { q: "What outputs `\"3.500000% 20\"`?", choices: ["System.out.printf(\"%f% %d\\n\", gpa, age);","System.out.printf(\"%f%% %d\\n\", gpa, age);","System.out.printf(\"%d%% %f\\n\", gpa, age);","System.out.printf(\"%f %% %d\\n\", gpa, age);","System.out.printf(\"%f%%%d\\n\", gpa, age);"], answer: 1, code: "String name = \"Alice\";\ndouble gpa = 3.5;\nint age = 20;", explanation: "%% is the escape sequence for a literal percent sign. A single % would be treated as the start of a format specifier." },
      { q: "What outputs `\"20, 21\"`?", choices: ["System.out.printf(\"%d, %d\\n\", age, age + 1);","System.out.printf(\"%d, %d\\n\", age);","System.out.printf(\"%d, %d\\n\", age, age);","System.out.printf(\"%d,%d\\n\", age, age + 1);","System.out.printf(\"%d, %d\\n\", age - 1, age);"], answer: 0, code: "String name = \"Alice\";\ndouble gpa = 3.5;\nint age = 20;", explanation: "%d takes the next argument in order: age = 20, then age + 1 = 21, giving '20, 21'. Don't forget the space after the comma!" },
      { q: "Does Line A immediately write to standard output?", choices: ["True","False"], answer: 1, code: "// Poem by Henry David Thoreau\nSystem.out.print(\"My life has been the poem \"); // A\nSystem.out.println(\"I would have writ\");         // B\nSystem.out.print(\"But I could not \");            // C\nSystem.out.flush();\nSystem.out.print(\"both live and utter it.\\n\");   // D", explanation: "print() buffers its output. Without a newline or explicit flush, the text just sits waiting in the buffer." },
      { q: "Does Line B immediately write to standard output?", choices: ["True","False"], answer: 0, code: "// Poem by Henry David Thoreau\nSystem.out.print(\"My life has been the poem \"); // A\nSystem.out.println(\"I would have writ\");         // B\nSystem.out.print(\"But I could not \");            // C\nSystem.out.flush();\nSystem.out.print(\"both live and utter it.\\n\");   // D", explanation: "println() triggers an auto-flush because System.out has autoFlush = true. The text appears on screen right away." },
      { q: "Does Line C immediately write to standard output?", choices: ["True","False"], answer: 1, code: "// Poem by Henry David Thoreau\nSystem.out.print(\"My life has been the poem \"); // A\nSystem.out.println(\"I would have writ\");         // B\nSystem.out.print(\"But I could not \");            // C\nSystem.out.flush();\nSystem.out.print(\"both live and utter it.\\n\");   // D", explanation: "print() without a newline just buffers again. The text waits in the buffer until something flushes it." },
      { q: "Does Line D immediately write to standard output?", choices: ["True","False"], answer: 0, code: "// Poem by Henry David Thoreau\nSystem.out.print(\"My life has been the poem \"); // A\nSystem.out.println(\"I would have writ\");         // B\nSystem.out.print(\"But I could not \");            // C\nSystem.out.flush();\nSystem.out.print(\"both live and utter it.\\n\");   // D", explanation: "When print() is called with a string containing '\\n', Java's PrintStream sees the newline and auto-flushes (because autoFlush = true on System.out)." },
    ]
  },
  {
    section: "Section 15.4",
    description: "Reading files with FileInputStream and Scanner — opening streams, hasNext() / hasNextInt() loops, reading full lines with nextLine(), and tracking statistics from file data.",
    title: "Section 15.4 — File Input (Scanner)",
    questions: [
      { q: "What is the error in the following code?", choices: ["The file stream is not big enough.","The file stream has not been properly opened.","The nextInt() method cannot be used here.","The code is fine."], answer: 1, code: "FileInputStream fbStream;\nScanner inFS;\nint[] num;\nint numElem = 0;\nint i = 0;\ninFS = new Scanner(fbStream);\nnumElem = inFS.nextInt();\nnum = new int[numElem];", explanation: "fbStream was declared but never assigned with 'new FileInputStream(...)'. Scanning from an unopened stream would crash." },
      { q: "Which statement opens a file inputfile.txt given `FileInputStream fbs = null;`", choices: ["fbs.FileInputStream(\"inputfile.txt\");","fbs(\"inputfile.txt\");","fbs = new FileInputStream(\"inputfile.txt\");","fbs = new FileInputStream.open(\"inputfile.txt\");","fbs = Scanner.open(\"inputfile.txt\");"], answer: 2, code: "FileInputStream fbs = null;", explanation: "'fbs = new FileInputStream(\"inputfile.txt\")' creates a new stream connected to that file. That's the correct constructor syntax." },
      { q: "Which statement determines if the next token in a file is an integer available to be read?", choices: ["fileNum = inFS.nextInt();","if (inFS.hasNextInt())","inFS.checkInt()","if (inFS.isInteger())","inFS.peekInt()"], answer: 1, code: "", explanation: "hasNextInt() peeks at the next token and returns true if it can be read as an integer — without actually consuming it." },
      { q: "Given a file with 7 tokens (words/numbers), how many times does the `while(inFS.hasNext())` loop iterate?", choices: ["3","4","7","14","2"], answer: 2, code: "// File contents:\n// twenty\n// associable\n// twenty\n// unredacted\n// associable\n// folksay\n// twenty", explanation: "hasNext() returns true once for each token. There are 7 tokens in the file, so the loop runs exactly 7 times." },
      { q: "What indicates that the end of the input file stream has been reached?", choices: ["The hasNext() method returning false","The hasNext() method returning true","The `hasNextLine()` method returning false","`inFS` becoming null","The Scanner constructor throwing an exception"], answer: 0, code: "", explanation: "hasNext() returns false when there are no more tokens to read — that's how you know you've reached the end of the file." },
      { q: "If the user entered \"associable\" as the userWord, how many times would the while loop execute?\n(File contains 7 words; \"associable\" appears twice)", choices: ["2","7","3","5","14"], answer: 1, code: "", explanation: "The while(inFS.hasNext()) loop runs once for every token in the file — all 7 — regardless of what userWord is. It doesn't stop early." },
      { q: "Which statement reads a full line of multiple strings from an input file?", choices: ["lineString = inFS.next();","lineString = inFS.nextLine();","lineString = inFS.readLine();","lineString = inFS.nextFullLine();","lineString = inFS.getLine();"], answer: 1, code: "", explanation: "next() reads one word at a time. nextLine() reads everything up to the end of the line, including spaces." },
      { q: "What variables are declared to track the average rating in the restaurant review system?", choices: ["A single double","Two integers","Two integers and a double","Three integers","One integer and two doubles"], answer: 2, code: "// Tracks userRatingSum, userRatingCount (ints), and computes double average", explanation: "You need an int for the running sum, an int for the count, and a double for the final average (sum ÷ count)." },
    ]
  },
  {
    section: "Section 15.5",
    description: "Writing files with FileOutputStream and PrintWriter — how PrintWriter wraps an OutputStream, why the file is created on open (not on write), and proper use of close().",
    title: "Section 15.5 — File Output (PrintWriter)",
    questions: [
      { q: "The `FileOutputStream` constructor takes _____.", choices: ["0 arguments","a String for a file name as an argument","a PrintWriter as an argument","an OutputStream as an argument","a File object as an argument"], answer: 1, code: "", explanation: "new FileOutputStream(\"filename\") takes a String filename. That's the one required argument to tell Java which file to open." },
      { q: "Which correctly initializes `outFS` to enable writing to outfile.txt using `PrintWriter`'s methods?", choices: ["outFS = new PrintWriter(outputStream);","outFS = PrintWriter(outputStream);","outFS = new FileOutputStream(outputStream);","outFS = new PrintWriter(\"outfile.txt\");","outputStream = new PrintWriter(outputStream);"], answer: 0, code: "FileOutputStream outputStream = new FileOutputStream(\"outfile.txt\");\nPrintWriter outFS = null;", explanation: "'outFS = new PrintWriter(outputStream)' wraps the FileOutputStream so you can use println() and printf() to write data." },
      { q: "The `PrintWriter` _____.", choices: ["is required to write to a FileOutputStream","opens a second file for writing","is used to allow data types other than byte arrays to be easily written to the file","automatically closes the FileOutputStream when done","converts the FileOutputStream to a BufferedWriter"], answer: 2, code: "", explanation: "PrintWriter lets you write ints, doubles, Strings, and more to a file easily, using familiar methods like println() and printf()." },
      { q: "An exception is thrown if \"myoutfile.txt\" cannot be opened.", choices: ["True","False"], answer: 0, code: "", explanation: "If the file path is wrong or the file is locked, FileOutputStream throws an exception to warn you that opening failed." },
      { q: "Since no data is written, the code below never creates the myoutfile.txt file on disk.", choices: ["True","False"], answer: 1, code: "fileStream = new FileOutputStream(\"myoutfile.txt\");\nfileStream.close();", explanation: "Calling 'new FileOutputStream(...)' creates the file on disk immediately — even before any data is written to it!" },
      { q: "A `FileOutputStream` should be closed using the `close()` method.", choices: ["True","False"], answer: 0, code: "", explanation: "Always close your streams when done. Without close(), the file might be incomplete or not properly saved." },
      { q: "The `PrintWriter` constructor _____.", choices: ["has a parameter of type OutputStream","has no parameters","has a parameter of type String","has a parameter of type FileInputStream","has two parameters: OutputStream and boolean"], answer: 0, code: "", explanation: "PrintWriter(OutputStream out) is the constructor — it takes any OutputStream as its parameter to wrap." },
      { q: "A `PrintWriter` can be created from either `fileStream` or `System.out` because _____.", choices: ["both are instances of FileOutputStream","both are instances of a class that inherits from OutputStream","both are instances of PrintWriter","both are final classes in java.io","both support buffered I/O by default"], answer: 1, code: "", explanation: "Both FileOutputStream and PrintStream (what System.out is) are children of OutputStream. PrintWriter can wrap any OutputStream!" },
      { q: "`println()` is a method of _____.", choices: ["the OutputStream class","the PrintWriter class","both the OutputStream and PrintWriter classes","the PrintStream class","the Formatter class"], answer: 1, code: "", explanation: "PrintWriter has its own println() for writing to files. This question is asking specifically about the PrintWriter class." },
    ]
  },
  {
    section: "Section 16.1",
    description: "Exception basics — which inputs trigger InputMismatchException when using Scanner, and how unhandled exceptions affect program flow.",
    title: "Section 16.1 — Exception Basics",
    questions: [
      { q: "Which input causes an exception for this code?", choices: ["12 34 two","43 -7","17 two 3","17 3 two","5 10"], answer: 2, code: "int num1 = 0, num2 = 0;\nnum1 = scnr.nextInt();\nnum2 = scnr.nextInt();", explanation: "'17 two 3': nextInt() reads 17 fine, then tries to read 'two' as an integer — but 'two' is a word, causing InputMismatchException!" },
      { q: "Which input also causes an exception when reading two integers?", choices: ["5 13","35 45.1","12    34","-5 13","999 1"], answer: 1, code: "int num1 = 0, num2 = 0;\nnum1 = scnr.nextInt();\nnum2 = scnr.nextInt();", explanation: "'35 45.1': nextInt() reads 35, then tries to read '45.1' as an integer — but integers can't have decimal points!" },
      { q: "Which input causes an exception when reading a double?", choices: ["+5 0","1,0 23","1000 23000","3.14","-5.5 10"], answer: 1, code: "distMiles = scnr.nextDouble();", explanation: "'1,0 23': Scanner sees '1,0' as one token, but a comma between digits isn't valid in Java's default double format — InputMismatchException!" },
    ]
  },
  {
    section: "Section 16.2",
    description: "Throwing and catching exceptions — throw new Exception(), getMessage() vs toString(), catch block matching rules, and ordering multiple catch blocks correctly.",
    title: "Section 16.2 — Throwing and Catching Exceptions",
    questions: [
      { q: "Which statement throws an `Exception` object with the message `\"Invalid ID\"`?", choices: ["throw Exception(\"Invalid ID\");","throw new Exception();","throw new Exception(\"Invalid ID\");","Exception.throw(\"Invalid ID\");","new Exception(\"Invalid ID\");"], answer: 2, code: "", explanation: "You need 'throw new Exception(\"message\")'. The 'new' keyword creates the Exception object, and the message goes inside the parentheses." },
      { q: "Which statement outputs only the message of an exception object named `excpt`?", choices: ["System.out.println(excpt.toString());","System.out.println(excpt.getMessage());","System.out.println(excpt);","System.out.println(excpt.getError());","System.out.println(excpt.description());"], answer: 1, code: "", explanation: "getMessage() returns just the message you passed in. toString() includes the exception class name too — much longer and more info than needed." },
      { q: "Which catch block catches the exception thrown by this throw statement?", choices: ["catch ( Exception excpt ) { // ... }","catch ( InputMismatchException excpt ) { // ... }","catch ( ArithmeticException excpt ) { // ... }","catch ( NullPointerException excpt ) { // ... }","catch ( NumberFormatException excpt ) { // ... }"], answer: 0, code: "throw new Exception(\"0.0 / 0.0 is not a number\");", explanation: "The throw creates a base Exception object, not InputMismatchException or ArithmeticException. Only 'catch(Exception)' is broad enough to match it." },
      { q: "In the `CircleRadiusCalculator` program, what is output when the input is the word `\"pi\"`?", choices: ["Invalid input.","Invalid area.","Invalid area. Invalid input.","1.0","Area: 3.14"], answer: 0, code: "import java.util.Scanner;\nimport java.util.InputMismatchException;\n\npublic class CircleRadiusCalculator {\n    public static void main(String[] args) {\n        Scanner scnr = new Scanner(System.in);\n        try {\n            System.out.print(\"Enter radius: \");\n            double radius = scnr.nextDouble();\n            if (radius <= 0.0)\n                throw new Exception(\"Invalid area.\");\n            double area = Math.PI * radius * radius;\n            System.out.printf(\"Area: %.2f%n\", area);\n        } catch (InputMismatchException e) {\n            System.out.println(\"Invalid input.\");\n        } catch (Exception e) {\n            System.out.println(e.getMessage());\n        }\n    }\n}", explanation: "'pi' is not a number, so nextDouble() throws InputMismatchException. The first catch block matches it and prints 'Invalid input.'" },
      { q: "Which handler arrangement catches exceptions of type `Exception` and `InputMismatchException`?", choices: ["catch ( InputMismatchException excpt1, Exception excpt2 ) { // ... }","catch ( InputMismatchException ) { // ... }\ncatch ( Exception ) { // ... }","catch ( Exception excpt ) { // ... }","catch ( Exception excpt ) { }\ncatch ( InputMismatchException excpt ) { }","catch ( RuntimeException excpt ) { }"], answer: 2, code: "", explanation: "InputMismatchException is a type of Exception, so one 'catch(Exception)' catches both. The other options below it would be unreachable." },
      { q: "Which handler arrangement can catch exceptions of type `Exception` and `InputMismatchException` in SEPARATE catch blocks?", choices: ["catch ( Exception excpt ) { // ... }\ncatch ( InputMismatchException excpt ) { // ... }","catch ( InputMismatchException excpt ) { // ... }\ncatch ( Exception excpt ) { // ... }","catch ( Exception excpt ) { // ... }\ncatch ( Exception excpt ) { // ... }","catch ( RuntimeException excpt ) { // ... }\ncatch ( Exception excpt ) { // ... }","catch ( InputMismatchException excpt ) { // ... }\ncatch ( RuntimeException excpt ) { // ... }"], answer: 1, code: "", explanation: "More specific exceptions must come BEFORE broader ones. InputMismatchException goes first, then Exception catches everything else." },
    ]
  },
  {
    section: "Section 16.3",
    description: "File exceptions — FileNotFoundException scenarios, which files get left open when exceptions occur mid-execution, and how try-with-resources fixes resource leaks.",
    title: "Section 16.3 — Exceptions with Files",
    questions: [
      { q: "Which statement correctly opens file1.txt for reading? (File and program are in same directory.)", choices: ["fileInStream = new FileInputStream ( \"my-files/file1.txt\" );","fileInStream = new FileInputStream ( \"file1.txt\" );","fileInStream = new FileInputStream ( \"fiel1.txt\" );","fileInStream = new FileInputStream ( \"FILES/file1.txt\" );","fileInStream = new Scanner ( \"file1.txt\" );"], answer: 1, code: "", explanation: "When the file is in the same directory, just use the filename directly: new FileInputStream(\"file1.txt\"). No path prefix needed." },
      { q: "Which of the following would NOT throw a `FileNotFoundException`?", choices: ["Opening a read-only file for writing.","Specifying the wrong file path.","Reading invalid data from a file.","Providing a file name that exceeds 255 characters.","Opening a file that is already open by another process."], answer: 2, code: "", explanation: "FileNotFoundException is about finding or opening the FILE. Reading bad data inside a file causes a different exception entirely." },
      { q: "Which try/catch block correctly catches a potential `FileNotFoundException` when opening an input file?", choices: ["fileStream = new FileInputStream ( fileName );\ntry {\n    fileScnr = new Scanner ( fileStream );\n}\ncatch ( FileNotFoundException e ) { }","try {\n    fileScnr = new Scanner ( new FileInputStream ( fileName ));\n}\ncatch ( FileNotFoundException e ) { }","fileStream = new FileInputStream ( fileName );\nfileScnr = new Scanner ( fileStream );\ntry {\n    double numVal = fileScnr.nextDouble();\n}\ncatch ( FileNotFoundException e ) { }","try {\n    fileStream = new FileInputStream ( fileName );\n}\ncatch ( FileNotFoundException e ) {\n    fileScnr = new Scanner ( fileStream );\n}","new Scanner ( new FileInputStream ( fileName ) );"], answer: 1, code: "", explanation: "The FileInputStream constructor is the one that throws FileNotFoundException. It must be inside the try block to be caught properly." },
      { q: "The input file is not found. Which file(s) are left open?", choices: ["Only input.txt","Only output.txt","Both files are left open","No file is left open","The program terminates without executing any catch block."], answer: 3, code: "// Code WITHOUT try-with-resources:\n// fileInStream = new FileInputStream(\"input.txt\");\n// fileWriter = new PrintWriter(new FileOutputStream(\"output.txt\"));\n// catch(FileNotFoundException) only — no finally", explanation: "FileInputStream(\"input.txt\") throws FileNotFoundException before any file is opened. The catch block runs — no files are left open." },
      { q: "The input file is found, but the output file cannot be opened. Which file(s) are left open?", choices: ["Only input.txt","Only output.txt","Both files are left open","No file is left open","The program terminates without executing any catch block."], answer: 0, code: "// Code WITHOUT try-with-resources:\n// fileInStream = new FileInputStream(\"input.txt\");\n// fileWriter = new PrintWriter(new FileOutputStream(\"output.txt\"));\n// catch(FileNotFoundException) only — no finally", explanation: "input.txt opened successfully, then FileOutputStream(\"output.txt\") throws FileNotFoundException. Without a 'finally' block, input.txt stays open — a resource leak!" },
      { q: "Both input and output files are opened, but an `InputMismatchException` is thrown while reading. Which file(s) are left open?", choices: ["Only input.txt","Only output.txt","Both files are left open","No file is left open","The program terminates without executing any catch block."], answer: 2, code: "// Code WITHOUT try-with-resources:\n// fileInStream = new FileInputStream(\"input.txt\");\n// fileWriter = new PrintWriter(new FileOutputStream(\"output.txt\"));\n// catch(FileNotFoundException) only — no finally", explanation: "Both files are already open. InputMismatchException isn't caught by the FileNotFoundException handler, so both files leak — neither gets closed!" },
      { q: "Which try/catch blocks do NOT properly close the file input.txt?", choices: ["try ( Scanner scnr = new Scanner ( new FileInputStream ( fName )))\n{\n}\ncatch ( FileNotFoundException e ) { }","try ( FileInputStream inStrm = new FileInputStream ( fName );\n      Scanner scnr = new Scanner ( inStrm ))\n{\n}\ncatch ( FileNotFoundException e ) { }\ncatch ( IOException e ) { }","try ( Scanner scnr = new Scanner ( inStrm );\n      FileInputStream inStrm = new FileInputStream ( fName ))\n{\n}\ncatch ( FileNotFoundException e ) { }","try ( FileInputStream inStrm = new FileInputStream ( fName ))\n{\n}\ncatch ( IOException e ) { }","try ( FileInputStream inStrm = new FileInputStream ( fName );\n      Scanner scnr = new Scanner ( inStrm ))\n{\n}\ncatch ( IOException e ) { }"], answer: 2, code: "", explanation: "Choice C tries to create Scanner using 'inStrm' before 'inStrm' is declared — that's a forward reference compile error, so the file is never properly managed." },
      { q: "Which try/catch blocks properly close the file input.txt?", choices: ["try {\n    FileInputStream inStrm = new FileInputStream ( fName );\n    Scanner scnr = new Scanner ( inStrm );\n}\ncatch ( FileNotFoundException e ) { }\ncatch ( IOException e ) { }","try ( Scanner scnr = new Scanner ( inStrm ))\n{\n    FileInputStream inStrm = new FileInputStream ( fName );\n}\ncatch ( FileNotFoundException e ) { }\ncatch ( IOException e ) { }","FileInputStream inStrm = new FileInputStream ( fName );\ntry {\n    Scanner scnr = new Scanner ( inStrm );\n}\ncatch ( FileNotFoundException e ) { }\ncatch ( IOException e ) { }","try ( FileInputStream inStrm = new FileInputStream ( fName );\n      Scanner scnr = new Scanner ( inStrm ))\n{\n}\ncatch ( FileNotFoundException e ) { }\ncatch ( IOException e ) { }","FileInputStream inStrm = new FileInputStream ( fName );\nScanner scnr = new Scanner ( inStrm );\ntry { }\ncatch ( FileNotFoundException e ) { }\ncatch ( IOException e ) { }"], answer: 3, code: "", explanation: "Both FileInputStream and Scanner are in the try-with-resources header — Java automatically closes both when the try block exits, even if an exception is thrown!" },
    ]
  },
  {
    section: "Section 16.5",
    description: "Exception handling pitfalls — catch block ordering errors where a broad Exception swallows specific types, and inputs that trigger unintended exception paths.",
    title: "Section 16.5 — Exception Handling Pitfalls",
    questions: [
      { q: "Which input sequence causes an unintended exception type to be caught?", choices: ["-1.0 10.0","0.0 0.0","20 twenty","1.0 2.0","10.0 5.0"], answer: 2, code: "// DensityCalculator — main() uses a too-broad catch block:\ntry {\n    System.out.printf(\"Density: %.4f%n\", getDensity(scnr));\n} catch (Exception e) {\n    // catches EVERYTHING — including InputMismatchException\n    System.out.println(\"Error: \" + e.getMessage());\n}\n\n// getDensity() can throw:\n//   InvalidNegativeInputException — if mass or volume < 0\n//   NaNException                  — if density is NaN (0.0/0.0)", explanation: "'20 twenty': nextDouble reads 20.0, then 'twenty' isn't a number — InputMismatchException fires, but the too-broad catch(Exception) grabs it instead of the intended handlers." },
      { q: "Which scenario causes an unintended exception type to be caught in `getDensity()`?", choices: ["The scnr parameter in getDensity() is null.","The input sequence 0.0 10.0","The input sequence 10.0 0.0","The input sequence -5.0 10.0","The input sequence 1.0 -3.0"], answer: 0, code: "// DensityCalculator — main() uses a too-broad catch block:\ntry {\n    System.out.printf(\"Density: %.4f%n\", getDensity(scnr));\n} catch (Exception e) {\n    // catches EVERYTHING — including NullPointerException\n    System.out.println(\"Error: \" + e.getMessage());\n}\n\n// getDensity() can throw:\n//   InvalidNegativeInputException — if mass or volume < 0\n//   NaNException                  — if density is NaN (0.0/0.0)", explanation: "If scnr is null, calling scnr.nextDouble() throws NullPointerException — an unintended bug that the overly broad catch(Exception) quietly swallows." },
      { q: "Does the following catch block arrangement handle the NaN exception separately from other exception types?", choices: ["Yes","No"], answer: 1, code: "catch ( Exception e ) { }\ncatch ( InputMismatchException e ) { }\ncatch ( NullPointerException e ) { }", explanation: "No! Exception comes first and catches absolutely everything. The InputMismatchException and NullPointerException catches below it are never reached." },
      { q: "Does the following catch block arrangement handle the NaN exception separately from other exception types?", choices: ["Yes","No"], answer: 1, code: "catch ( InputMismatchException e ) { }\ncatch ( Exception e ) { }", explanation: "InputMismatchException has its own catch, but NaNException falls into the broad 'catch(Exception)' along with NullPointerException and everything else. Not separate." },
    ]
  },
  {
    section: "Section 17.1",
    description: "Introduction to recursion — distinguishing recursive algorithms (self-referential, smaller subproblem) from iterative step-by-step instructions.",
    title: "Section 17.1 — Recursion Introduction",
    questions: [
      { q: "Is the following algorithm recursive?\n\"Helping N people:\nIf N is 1, help that person.\nElse, help the first N/2 people, then help the second N/2 people.\"", choices: ["True","False"], answer: 0, code: "", explanation: "Yes! 'Help the first N/2 people' calls the same task on a smaller group — that's the definition of recursion: solving a problem by solving a smaller version of itself." },
      { q: "Is the following algorithm recursive?\n\"Driving to the store:\nGo 1 mile.\nTurn left on Main Street.\nGo 1/2 mile.\"", choices: ["True","False"], answer: 1, code: "", explanation: "No recursion here — it's just a step-by-step list. No part says 'do this same process again on a smaller version'. That's just a loop or sequence." },
      { q: "Is the following algorithm recursive?\n\"Sorting envelopes by zipcode:\nIf N is 1, done.\nElse, find the middle zipcode. Put all less on the left, greater on the right. Then sort the left, then sort the right.\"", choices: ["True","False"], answer: 0, code: "", explanation: "'Sort the left half, sort the right half' uses the same sorting process on smaller groups — that's recursive!" },
    ]
  },
  {
    section: "Section 17.3",
    description: "Recursive binary search — how findMatch() splits the search range at the midpoint each call and what happens at each level of the call stack.",
    title: "Section 17.3 — Binary Search (Recursive)",
    questions: [
      { q: "To search for item C, the first call is `findMatch(0, 4)`. What is the second call to `findMatch()`?", choices: ["findMatch(0, 0)","findMatch(0, 2)","findMatch(3, 4)","findMatch(1, 4)","findMatch(2, 4)"], answer: 1, code: "// Array has 5 items at indices 0-4\n// midVal = (0+4)/2 = 2\n// C is before midpoint, so search lower half", explanation: "The midpoint of [0,4] is index 2. C is before that, so we search the lower half: findMatch(0, 2)." },
      { q: "In searching for item C, `findMatch(0, 2)` is called. What happens next?", choices: ["Base case 1: item found at midVal.","Base case 2: rangeSize == 1, so no match.","Recursive call: findMatch(2, 2)","Recursive call: findMatch(0, 1)","Base case 1: item found at index 0."], answer: 2, code: "// midVal = (0+2)/2 = 1\n// item at index 1 is not C\n// C is after index 1, so recurse on upper half", explanation: "Midpoint of [0,2] is index 1. C is after index 1, so we recurse on the upper half: findMatch(2, 2)." },
    ]
  },
  {
    section: "Section 17.4",
    description: "Debugging recursion — using an indent parameter to visually trace call depth; each recursive call deepens the indent, which is trimmed on return.",
    title: "Section 17.4 — Recursive Debugging",
    questions: [
      { q: "The debug approach described requires an extra parameter to be passed to indicate the amount of indentation.", choices: ["True","False"], answer: 0, code: "", explanation: "The debug trick adds an indent string parameter (like spaces) that gets passed to each call so you can see how deep the recursion goes." },
      { q: "Each recursive call should add a few spaces to the indent parameter.", choices: ["True","False"], answer: 0, code: "", explanation: "Deeper recursion = more indentation. Each recursive call adds a few spaces so the output looks like a tree." },
      { q: "The method should remove a few spaces from the indent parameter before returning.", choices: ["True","False"], answer: 0, code: "", explanation: "When a call finishes and returns, you trim the spaces back so the output aligns correctly and shows the call going back up." },
    ]
  },
  {
    section: "Section 17.5",
    description: "Recursive algorithm design — the necessity of base cases, having multiple base cases, and why recursive factorial is not faster than a loop.",
    title: "Section 17.5 — Recursive Algorithm Design",
    questions: [
      { q: "Recursive methods can be accomplished in one step, namely repeated calls to itself.", choices: ["True","False"], answer: 1, code: "", explanation: "Recursion needs at least TWO things: a base case (to stop) and a recursive call (to keep going). One step alone isn't enough." },
      { q: "A recursive method with parameter N counts up from any negative number to 0. An appropriate base case would be `N == 0`.", choices: ["True","False"], answer: 0, code: "", explanation: "If the method counts from a negative number up to 0, stopping at N == 0 makes perfect sense — that's a valid base case." },
      { q: "A recursive method can have two base cases, such as `N == 0` returning 0, and `N == 1` returning 1.", choices: ["True","False"], answer: 0, code: "", explanation: "A recursive method can have as many base cases as needed! N == 0 returning 0 and N == 1 returning 1 is exactly how Fibonacci works." },
      { q: "`N!` (N factorial) is commonly implemented as a recursive method due to being easier to understand and executing faster than a loop implementation.", choices: ["True","False"], answer: 1, code: "", explanation: "Recursive factorial is elegant and easy to read, but NOT faster than a loop. Each function call adds overhead, making it actually slower." },
    ]
  },
  {
    section: "Section 17.6",
    description: "Recursive GCD — how the Euclidean algorithm recurses with gcd(b, a%b) and what constitutes its base case.",
    title: "Section 17.6 — GCD (Recursive)",
    questions: [
      { q: "How many calls are made to `gcdCalculator()` for input values 12 and 8?\n(GCD(12,8): 12%8=4 → GCD(8,4): 8%4=0 → base case)", choices: ["1","2","3","4","5"], answer: 2, code: "// GCD(12, 8) -> GCD(8, 4) -> GCD(4, 0) = base case\n// Total: 3 calls", explanation: "GCD(12,8) → GCD(8,4) → GCD(4,0). That's three separate function calls before hitting the base case." },
      { q: "What is the base case for the GCD algorithm?", choices: ["When both inputs to the method are equal.","When both inputs are greater than 1.","When inNum1 > inNum2.","When one input is 0.","When the remainder is negative."], answer: 3, code: "", explanation: "The base case is when one input is 0. In our example, GCD(4, 0) is the base case — it returns 4 directly without another recursive call." },
    ]
  },
  {
    section: "Section 17.7",
    description: "Permutation generation — scrambleLetters() builds all orderings of a string; shoppingBagPermutations() picks fixed-size subsets from a larger set. Questions share one code example, so read each one in context.",
    title: "Section 17.7 — Permutations (Recursive)",
    questions: [
      { q: "What is the output of `scrambleLetters(\"xy\", \"\")`?\n(Trace the recursion manually)", choices: ["yx xy","xx yy xy yx","xy yx","xy","yx"], answer: 2, code: "// i=0: remainLetters=\"y\", scramLetters=\"x\"\n//   -> prints \"xy\"\n// i=1: remainLetters=\"x\", scramLetters=\"y\"\n//   -> prints \"yx\"", explanation: "'xy' first (x placed first, then y fills in), then 'yx' (y placed first, then x). Both orderings are printed." },
      { q: "When `main()` calls `shoppingBagPermutations()`, how many items are in the remainingItems list?\n(possibleItems: Milk, Belt, Toys, Cups — 4 items)", choices: ["None","3","4","1","2"], answer: 2, code: "// possibleItems = [Milk, Belt, Toys, Cups]\n// MAX_SHOPPING_BAG_SIZE = 3", explanation: "When main first calls it, none have been picked yet. All 4 possible items (Milk, Belt, Toys, Cups) are in remainingItems." },
      { q: "When `main()` calls `shoppingBagPermutations()`, how many items are in the currBag list?", choices: ["None","1","4","2","3"], answer: 0, code: "", explanation: "The bag starts empty when main calls the method. Nothing is picked until the recursive calls begin filling it." },
      { q: "After `main()` calls `shoppingBagPermutations()`, what happens first?", choices: ["The base case prints Milk, Belt, Toys.","The method bags one item, makes recursive call.","The method bags 3 items, makes recursive call.","The method immediately returns without doing anything.","The method checks if remainingItems is empty first."], answer: 1, code: "", explanation: "The method picks one item from remainingItems into currBag, then makes a recursive call to fill the rest of the bag." },
      { q: "Just before `shoppingBagPermutations()` returns back to `main()`, how many items are in the remainingItems list?\n(Items are restored after each recursive call)", choices: ["None","4","1","2","3"], answer: 1, code: "", explanation: "Items are always put back after each recursive branch finishes. When we return to main, all 4 original items are back in remainingItems." },
      { q: "How many recursive calls occur before the first permutation is printed?\n(Need 3 items in bag before base case triggers)", choices: ["None","1","3","2","4"], answer: 2, code: "", explanation: "You need 3 items to fill the bag (MAX_SHOPPING_BAG_SIZE = 3). It takes 3 recursive calls to pick them all before printing." },
      { q: "What happens if `main()` only put 2, rather than 4, items in the possibleItems list?\n(`MAX_SHOPPING_BAG_SIZE` = 3)", choices: ["Base case never executes; nothing printed.","Infinite recursion occurs.","Only one permutation is printed.","The first two permutations are printed, then the program stops.","An exception is thrown."], answer: 0, code: "", explanation: "With only 2 items and needing 3 for the bag, you can never fill it. The base case never triggers, so nothing gets printed." },
      { q: "You wish to generate all possible 3-letter subsets from the letters in an N-letter word (N>3). Which recursive method is the closest?", choices: ["shoppingBagPermutations","scrambleLetters","main()","gcdCalculator","findMatch"], answer: 0, code: "", explanation: "shoppingBagPermutations picks a fixed number of items from a larger set — perfect for generating fixed-size subsets from a bigger collection." },
    ]
  },
  {
    section: "Section 17.8",
    description: "Stack overflow — how stack frames are allocated per call, why the stack is finite, and how infinite recursion (no base case) exhausts it.",
    title: "Section 17.8 — Stack Overflow",
    questions: [
      { q: "A memory's stack region can store at most one stack frame.", choices: ["True","False"], answer: 1, code: "", explanation: "The stack can hold many frames — one for each method call currently running. It's like a stack of plates, not just one." },
      { q: "The size of the stack is unlimited.", choices: ["True","False"], answer: 1, code: "", explanation: "The stack is a fixed chunk of memory. It can hold a lot of frames, but there's always a limit — it will run out eventually." },
      { q: "A stack overflow occurs when the stack frame for a method call extends past the end of the stack's memory.", choices: ["True","False"], answer: 0, code: "", explanation: "Exactly! When too many frames pile up and go past the stack's memory boundary, you get a StackOverflowError." },
      { q: "The following recursive method will result in a stack overflow.", choices: ["True","False"], answer: 0, code: "int recAdder(int inValue) {\n    return recAdder(inValue + 1);\n}", explanation: "recAdder calls itself forever — there's no base case to stop it! It keeps adding frames until memory runs out, causing a stack overflow." },
    ]
  },
  {
    section: "Section 19.1",
    title: "Section 19.1",
    questions: []
  },
  {
    section: "Section 19.2",
    title: "Section 19.2",
    questions: []
  },
  {
    section: "Section 34.1",
    title: "Section 34.1",
    questions: []
  },
  {
    section: "Section 34.2",
    title: "Section 34.2",
    questions: []
  },
  {
    section: "Section 34.3",
    description: "Binary search prerequisite — binarySearch() requires the input array to be sorted; unsorted input produces undefined behavior.",
    title: "Section 34.3 — Binary Search",
    questions: [
      { q: "The array (12, 75, 18, 22, 94, 16, 22) can be used as input to the `binarySearch()` method.", choices: ["True","False"], answer: 1, code: "// Binary search requires a SORTED array.\n// (12, 75, 18, 22, 94, 16, 22) is NOT sorted.", explanation: "Binary search requires a sorted array. (12, 75, 18, ...) is not sorted — using binarySearch() on it gives wrong or undefined results." },
    ]
  },
  {
    section: "Section 37.1",
    description: "Stack concept — LIFO ordering, and the semantics of Push, Pop, Peek, IsEmpty, and GetLength on an abstract stack.",
    title: "Section 37.1 — Stack Concept",
    questions: [
      { q: "Which sequence of operations produces numStack with 41 at the top?\n(Stack shown top-first: 41, 39, 88, 56)", choices: ["1) Push 41  2) Push 39  3) Push 88  4) Push 56","1) Push 56  2) Push 88  3) Push 39  4) Push 41","1) Push 56  2) Push 88  3) Push 41  4) Push 39","1) Push 41  2) Push 39  3) Push 56  4) Push 88","1) Push 88  2) Push 56  3) Push 39  4) Push 41"], answer: 1, code: "", explanation: "The last item pushed ends up on top. Push 56 first (bottom), then 88, 39, then 41 last (top). LIFO — Last In, First Out!" },
      { q: "Popping from numStack (top = 41) _____.", choices: ["returns 41","returns 56","causes an error","returns 39","returns 88"], answer: 0, code: "", explanation: "Pop removes and returns the top item. Since 41 is on top, Pop returns 41." },
      { q: "If four pop-and-print operations occur on numStack [top: 41, 39, 88, 56], what is printed?", choices: ["41, 39, 88, 56","56, 88, 39, 41","41, 41, 41, 41","41, 88, 39, 56","88, 39, 56, 41"], answer: 0, code: "", explanation: "Each Pop takes from the top: 41 first, then 39, then 88, then 56. Like lifting plates off a stack one by one." },
      { q: "Given inventoryStack: 70, 888, -3, 2\n`GetLength(inventoryStack)` returns _____.", choices: ["4","70","5","2","-3"], answer: 0, code: "", explanation: "GetLength just counts items: 70, 888, -3, 2 — that's 4 items." },
      { q: "Given callStack: 2, 9, 4 (2 = top)\nWhat are the contents after `Peek(callStack)`?", choices: ["2, 9, 4","9, 4","2","4, 9, 2","2, 9"], answer: 0, code: "", explanation: "Peek looks at the top item without removing it. The stack stays exactly the same: 2, 9, 4." },
      { q: "Given callStack: 2, 9, 4 (2 = top)\nWhat are the contents after `Pop(callStack)`?", choices: ["2, 9, 4","9, 4","2","9","4, 9, 2"], answer: 1, code: "", explanation: "Pop removes the top item (2). What's left in the stack: 9, 4." },
      { q: "`IsEmpty(integerStack)` returns _____ if integerStack contains no items.", choices: ["true","false","null","0","-1"], answer: 0, code: "", explanation: "An empty stack has nothing in it, so IsEmpty() returns true." },
      { q: "Which operation should usually be preceded by a check that the stack is not empty?", choices: ["Pop","Push","Peek","IsEmpty","GetLength"], answer: 0, code: "", explanation: "Always check before Popping! Calling Pop on an empty stack causes an error. Push always works — you're just adding something." },
    ]
  },
  {
    section: "Section 37.2",
    description: "Linked-list stack implementation — how a singly linked list's head pointer acts as the top, and what StackPush/StackPop change at the pointer level.",
    title: "Section 37.2 — Linked-List Stack",
    questions: [
      { q: "After: `Push(45)`, `Push(56)`, `Push(11)`, `Pop()`\nThe stack has three items.", choices: ["True","False"], answer: 1, code: "StackPush(stack, 45)\nStackPush(stack, 56)\nStackPush(stack, 11)\npoppedValue = StackPop(stack)  // removes 11", explanation: "Push 45, 56, 11 (3 items), then Pop removes 11 (the top). Only 2 items remain: 45 at bottom and 56 on top." },
      { q: "After the same operations, a pop operation would return 56.", choices: ["True","False"], answer: 0, code: "// Stack after operations: [45 (bottom), 56 (top)]", explanation: "After popping 11, the stack is [45 (bottom), 56 (top)]. The next Pop returns 56, which is now on top." },
      { q: "Instead of a \"top\" pointer, numStack could have a \"bottom\" pointer that points to the last node.", choices: ["True","False"], answer: 1, code: "", explanation: "A bottom pointer would make push and pop very slow — you'd have to walk the whole list each time. You need the TOP pointer for efficient O(1) operations." },
      { q: "A push operation changes the _____.", choices: ["stack's top node pointer","data value of the stack's top node","next pointer of the stack's top node","stack's bottom node pointer","the node count variable"], answer: 0, code: "StackPush(stack, item) {\n  newNode = Allocate new node\n  newNode.data = item\n  newNode.next = stack.top\n  stack.top = newNode   // <-- top pointer changes\n}", explanation: "Push creates a new node and makes it the new top. The stack's top pointer is updated to point to the new node." },
      { q: "Is numStack a valid linked-list-based stack? (Nodes: 54 → 8 → null, top points to 54)", choices: ["Yes, and the top item is 54","Yes, and the top item is 8","No, a stack must be represented vertically","No, a valid stack must have at least 3 nodes.","No, the head pointer must point to the bottom node."], answer: 0, code: "", explanation: "Yes! A singly linked list with the head/top pointing to node 54 is a perfectly valid stack. 54 is the item you'd pop first." },
      { q: "`StackPop()` returns the stack's top node.", choices: ["True","False"], answer: 1, code: "StackPop(stack) {\n  poppedItem = stack.top.data  // returns DATA, not node\n  stack.top = stack.top.next\n  return poppedItem\n}", explanation: "StackPop returns the DATA value from the top node (stack.top.data), not the node object itself." },
    ]
  },
  {
    section: "Section 37.3",
    description: "Array-based stack — bounded vs. unbounded stacks, when resize() triggers, amortized vs. worst-case complexity, and the ArrayStack constructor options.",
    title: "Section 37.3 — Array-Based Stack",
    questions: [
      { q: "In an unbounded array-based stack, when the array is reallocated, the length _____.", choices: ["increases by 1","doubles","decreases by 1","triples","stays the same"], answer: 1, code: "", explanation: "When resizing, the array doubles. Doubling means you resize less often — most pushes are fast, and the memory usage stays efficient." },
      { q: "When does a push operation resize the stack's array?", choices: ["When length == array.length","When length == array.length - 1","Every push operation resizes the stack's array","When length > array.length","Before every push operation"], answer: 0, code: "", explanation: "Push resizes when the array is completely full: length == array.length. At that point it needs more room to store the next item." },
      { q: "In theory, an unbounded stack can grow in length indefinitely. In reality, the stack can _____.", choices: ["also grow in length indefinitely","grow only until all distinct 32-bit integer values are pushed","grow only until the resize operation fails to allocate memory","grow until its length reaches Integer.MAX_VALUE","grow until its length reaches maxLength"], answer: 2, code: "", explanation: "Memory runs out eventually. When resize() can't allocate more memory, the stack can no longer grow — the system is out of space." },
      { q: "A bounded stack's maximum length and initial array length are always equal.", choices: ["True","False"], answer: 1, code: "", explanation: "A bounded stack has a fixed max, but the initial array might start smaller. It can grow up to maxLength without necessarily starting there." },
      { q: "A bounded stack implementation may throw an exception if a push operation occurs when full.", choices: ["True","False"], answer: 0, code: "", explanation: "If the bounded stack is full and you try to push, it throws an exception rather than resizing — there's no room left!" },
      { q: "Array-based stack implementations commonly reallocate when popping.", choices: ["True","False"], answer: 1, code: "", explanation: "Pop just decrements the length counter — no array changes needed. Reallocating on every pop would be very wasteful." },
      { q: "Which implementation(s) may need to reallocate the array to push an item?\n(A = unbounded, B = bounded)", choices: ["Implementation A only","Implementation B only","Both A and B","Neither A nor B","Only when the stack's current length is 0"], answer: 0, code: "", explanation: "Only the unbounded stack (A) resizes when full. The bounded stack (B) throws an exception instead of resizing." },
      { q: "Which implementation(s) may allow a push when `length == maxLength`?\n(A = unbounded with maxLength=-1, B = bounded)", choices: ["Implementation A only","Implementation B only","Neither A nor B","Both A and B","Only when the stack is empty"], answer: 2, code: "", explanation: "For unbounded A (maxLength = -1), length can never equal -1, so this scenario never happens. For bounded B, hitting maxLength means it's full — no push allowed. Neither case allows it." },
      { q: "Which implementation(s) guarantee that both push and pop execute in worst-case O(1) time?", choices: ["Implementation A only","Implementation B only","Both A and B","Neither A nor B","It depends on the initial array size."], answer: 1, code: "", explanation: "Only bounded (B) guarantees O(1) worst case for push since it never resizes. Unbounded (A) can trigger a resize that copies all n elements — that's O(n)." },
      { q: "The `ArrayStack` class implements _____.", choices: ["a bounded stack only","an unbounded stack only","both a bounded and unbounded stack","a fixed-size array","a dynamic array with a fixed cap"], answer: 2, code: "", explanation: "ArrayStack handles both modes: pass a maxLength argument for a bounded stack, or omit it for an unbounded stack." },
      { q: "Can the `ArrayStack` constructor be called without an argument?", choices: ["Yes. Doing so makes the stack bounded.","Yes. Doing so makes the stack unbounded.","No.","Yes. Doing so creates a stack with default max size 10.","Yes. Doing so creates an empty null-array stack."], answer: 1, code: "", explanation: "Yes! Calling the constructor with no argument creates an unbounded stack that can grow as large as memory allows." },
      { q: "The `pop()` method is implemented in two lines, but can also be implemented in one:", choices: ["return array[-- length];","return array[length --];","return array[length - 1];","return array[length];","return array[++length];"], answer: 0, code: "// Two-line version:\n// T toReturn = array[length - 1];\n// length--;\n// return toReturn;", explanation: "'return array[--length]' pre-decrements length first, then accesses the array at that new index — which is exactly the old top item." },
      { q: "The `pop()` method requires the stack length to be ≥ 1.", choices: ["True","False"], answer: 0, code: "", explanation: "You can't pop from an empty stack! The top item is at array[length - 1], which doesn't exist when length is 0." },
    ]
  },
  {
    section: "Section 37.4",
    description: "Queue concept — FIFO ordering, and the semantics of Enqueue, Dequeue, Peek, IsEmpty, and GetLength on an abstract queue.",
    title: "Section 37.4 — Queue Concept",
    questions: [
      { q: "Given rosterQueue: 400, 313, 270, 514, 119\n`GetLength(rosterQueue)` returns _____.", choices: ["400","5","119","1","3"], answer: 1, code: "", explanation: "Count the items: 400, 313, 270, 514, 119 — that's 5 items, so GetLength returns 5." },
      { q: "Which operation determines if the queue contains no items?", choices: ["IsEmpty()","Peek()","GetLength()","Dequeue()","Front()"], answer: 0, code: "", explanation: "IsEmpty() is the operation that checks if the queue has zero items. It returns true if empty, false if not." },
      { q: "Given parkingQueue: 1, 8, 3\nWhat are the queue contents after `Peek(parkingQueue)`?", choices: ["1, 8, 3","8, 3","1","1, 8","3"], answer: 0, code: "", explanation: "Peek looks at the front item without removing it. The queue stays exactly the same: 1, 8, 3." },
      { q: "Given parkingQueue: 2, 9, 4\nWhat are the queue contents after `Dequeue(parkingQueue)`?\n(Dequeue removes front item)", choices: ["9, 4","2, 9, 4","2","9","4, 9, 2"], answer: 0, code: "", explanation: "Dequeue removes the FRONT item (FIFO — first in, first out). The front is 2, so after dequeue: 9, 4 remain." },
      { q: "Given that parkingQueue has no items (is empty), what does `GetLength(parkingQueue)` return?", choices: ["-1","0","Undefined","1","The queue throws an exception."], answer: 1, code: "", explanation: "An empty queue has 0 items. GetLength on an empty queue returns 0." },
    ]
  },
  {
    section: "Section 37.5",
    description: "Linked-list queue implementation — front and end pointer roles, how Enqueue appends to the tail, and how Dequeue removes from the front.",
    title: "Section 37.5 — Linked-List Queue",
    questions: [
      { q: "The queue is empty when the front pointer is _____.", choices: ["null","not null","pointing to the first element","pointing to the last element","equal to 0"], answer: 0, code: "", explanation: "When front is null, it points to nothing — there's no first node, so the queue is empty." },
      { q: "In the `QueueDequeue()` operation, dequeuedItem is assigned with the list _____ node's data.", choices: ["front","end","head","tail","second"], answer: 0, code: "", explanation: "Dequeue grabs the data from the front node (the oldest item), then moves the front pointer to the next node." },
      { q: "For `QueueEnqueue(numQueue, 22)`, which pointer is updated to point to newNode?", choices: ["numQueue's front pointer","The front node's next pointer","The end node's next pointer","The new node's next pointer","numQueue's length counter"], answer: 2, code: "", explanation: "To add a new node at the end, the CURRENT end node's next pointer is updated to link to the new node." },
    ]
  },
  {
    section: "Section 37.6",
    description: "Array-based circular queue — frontIndex arithmetic, how resize() reorders elements, bounded vs. unbounded behavior, and the complexity of enqueue/dequeue. Questions share the same array state, read them in order.",
    title: "Section 37.6 — Array-Based Queue",
    questions: [
      { q: "What is the queue's front item if `frontIndex` is 3 and `length` is 2?\n(Array: [67, 44, 38, _] indexed 0-3)", choices: ["67","44","38","19","0"], answer: 2, code: "// front item = array[frontIndex] = array[3]\n// Array contents: index 0=67, 1=19, 2=44, 3=38", explanation: "The front item is always at array[frontIndex]. With frontIndex = 3, array[3] = 38 is the front." },
      { q: "What is the queue's back item if `frontIndex` is 0 and `length` is 3?\n(Array: [67, 19, 44, 38] indexed 0-3)", choices: ["67","44","38","19","0"], answer: 1, code: "// back item = array[(frontIndex + length - 1) % array.length]\n// = array[(0 + 3 - 1) % 4] = array[2] = 44", explanation: "Back index = (0 + 3 - 1) % 4 = 2. array[2] = 44 is the back item." },
      { q: "What is the queue's content if `length` is 4 and `frontIndex` is 1?\n(Array: [67, 19, 44, 38] indexed 0-3)", choices: ["(front) 67, 19, 44, 38 (back)","(front) 19, 44, 38 (back)","(front) 19, 44, 38, 67 (back)","(front) 44, 38, 67, 19 (back)","(front) 67, 19, 44, 38, 0 (back)"], answer: 2, code: "// Items: array[1]=19, array[2]=44, array[3]=38, array[0]=67 (wraps)\n// Queue content (front to back): 19, 44, 38, 67", explanation: "Start at index 1, go forward wrapping around: array[1]=19, array[2]=44, array[3]=38, then array[0]=67. Front to back: 19, 44, 38, 67." },
      { q: "_____ can be full.", choices: ["Only a bounded queue","Only an unbounded queue","Both bounded and unbounded queues","Neither a bounded nor unbounded queue","Only a queue with integer elements"], answer: 0, code: "", explanation: "Only a bounded queue has a maxLength cap. Unbounded queues resize when full, so they never truly fill up." },
      { q: "A bounded queue implementation may throw an exception if an enqueue operation occurs when full.", choices: ["True","False"], answer: 0, code: "", explanation: "A bounded queue has a hard limit. Trying to add more than maxLength items throws an exception — no room left!" },
      { q: "The `maxLength` variable is needed _____.", choices: ["only for the bounded queue implementation","only for the unbounded queue implementation","for both the bounded and unbounded queue implementations","only when the queue is full","only when the array needs to be resized"], answer: 0, code: "", explanation: "Only the bounded queue needs maxLength to know when it's full. An unbounded queue grows without limit and doesn't need a cap." },
      { q: "queueA (array: [73,91,87,62], frontIndex: 2, length: 4, `maxLength`: -1) is _____.", choices: ["bounded and full","bounded and not full","unbounded","unbounded and full","bounded with maxLength = 4"], answer: 2, code: "// maxLength = -1 means unbounded\n// length == array.length means array is full but can resize", explanation: "maxLength = -1 is the signal for 'no maximum limit' — this is an unbounded queue. It will resize rather than reject new items." },
      { q: "After executing `queueA.resize()`, queueA's allocation size is _____.\n(array: [73,91,87,62], frontIndex: 2, length: 4, maxLength: -1)", choices: ["-1","4","8","6","2"], answer: 2, code: "// newSize = array.length * 2 = 4 * 2 = 8\n// maxLength = -1 (no cap)", explanation: "resize() doubles the array: 4 × 2 = 8. The new array has 8 slots." },
      { q: "After executing `queueA.resize()`, queueA's first four array elements are _____.\n(array: [73,91,87,62], frontIndex: 2)", choices: ["73, 91, 87, 62","87, 62, 73, 91","91, 87, 62, 73","62, 73, 91, 87","73, 87, 62, 91"], answer: 1, code: "// Copies from frontIndex=2:\n// i=0: (2+0)%4=2 -> 87\n// i=1: (2+1)%4=3 -> 62\n// i=2: (2+2)%4=0 -> 73\n// i=3: (2+3)%4=1 -> 91\n// Result: [87, 62, 73, 91]", explanation: "resize() reorders elements starting from frontIndex = 2: copies array[2]=87, array[3]=62, array[0]=73, array[1]=91." },
      { q: "Can one of queueA's initial variables be changed such that executing `queueA.resize()` makes queueA's allocation size 6?", choices: ["Yes, if maxLength were initially 6","Yes, if array.length were initially 6","No","Yes, if length were initially 3","Yes, if frontIndex were initially 0"], answer: 0, code: "// newSize = 4*2 = 8\n// if maxLength=6: newSize = min(8, 6) = 6 ✓", explanation: "If maxLength = 6, resize() caps the new size at min(8, 6) = 6. Changing maxLength to 6 does the trick." },
      { q: "_____ may resize the queue.", choices: ["Only the enqueue operation","Only the dequeue operation","Both the enqueue and dequeue operations","Neither operation","Only when the queue is empty"], answer: 0, code: "", explanation: "Only enqueue can trigger a resize (when the array is full). Dequeue just updates frontIndex — no array changes needed." },
      { q: "`(frontIndex + length) % array.length` yields the index _____.", choices: ["of the item to remove during a dequeue operation","at which to insert a new item during an enqueue operation","of the queue's back item","of the queue's front item","of the middle item"], answer: 1, code: "", explanation: "(frontIndex + length) % array.length computes the next empty slot — exactly where the new item goes during enqueue." },
      { q: "`enqueue()` returns false if _____.", choices: ["the item is successfully enqueued","the resize operation fails","the queue is full","the queue is empty","the item is null"], answer: 2, code: "boolean enqueue(int item) {\n  if (length == maxLength) { return false; }  // bounded & full\n  if (length == array.length) { resize(); }\n  // ...\n  return true;\n}", explanation: "When the bounded queue is full (length == maxLength), enqueue can't add more items and returns false." },
      { q: "The `enqueue` operation's worst-case runtime complexity is _____.", choices: ["O(1)","O(log n)","O(n)","O(n²)","O(1) amortized"], answer: 2, code: "// Resize copies all n elements → O(n) worst case", explanation: "When the array must be resized, enqueue copies all n elements to a new array. That's O(n) in the worst case." },
      { q: "The `dequeue` operation's worst-case runtime complexity is _____.", choices: ["O(1)","O(log n)","O(n)","O(n²)","O(1) amortized"], answer: 0, code: "// Just adjusts frontIndex and decrements length → O(1)", explanation: "Dequeue just adjusts frontIndex and decrements length — constant work no matter how big the queue. That's O(1)." },
      { q: "An alternate implementation could store the queue's back item index instead of the length.", choices: ["True","False"], answer: 0, code: "", explanation: "Yes! Instead of storing length, you could store the back item's index. Some implementations work this way — both approaches are valid." },
    ]
  },
  {
    section: "Section 46.5",
    description: "Advanced Scanner usage — useDelimiter(\"\") for character-by-character reading, the nextLine() pitfall after nextInt(), and strategies for parsing multi-word fields.",
    title: "Section 46.5 — Scanner Advanced",
    questions: [
      { q: "Select the output: Scanner counts ALL characters in \"A cup of Java.\" using `useDelimiter(\"\")`.", choices: ["4","7","11","14","10"], answer: 3, code: "data.useDelimiter(\"\");\nint count = 0;\nwhile (data.hasNext()) {\n    String input = data.next();\n    count++;\n}\nSystem.out.println(count);\n// Input: \"A cup of Java.\"  (14 characters)", explanation: "'A cup of Java.' has exactly 14 characters (letters + spaces + period). useDelimiter(\"\") makes each character its own token." },
      { q: "Select the output: Scanner counts NON-LETTER characters in \"A cup of Java.\" using `useDelimiter(\"\")` and `Character.isLetter()`.", choices: ["3","4","10","14","7"], answer: 1, code: "// Non-letters in \"A cup of Java.\": 3 spaces + 1 period = 4\ndata.useDelimiter(\"\");\nint count = 0;\nwhile (data.hasNext()) {\n    char input = data.next().charAt(0);\n    if (!Character.isLetter(input)) { count++; }\n}\nSystem.out.println(count);", explanation: "Non-letters in 'A cup of Java.' are: 3 spaces + 1 period = 4 non-letter characters." },
      { q: "For input \"China  1330044605\", is this approach valid?\nFind the FIRST space at position i, then extract `line.substring(0, i).trim()` and `line.substring(i + 1)`.", choices: ["Valid","Not valid"], answer: 1, code: "// Approach: split on FIRST space\n// Works for: \"China  1330044605\"  →  country=\"China\", pop=\"1330044605\"\n// Fails for: \"United States 303824646\"  →  country=\"United\", pop=\"States 303824646\"", explanation: "Splitting on the FIRST space fails for multi-word country names like 'United States' — it would treat 'United' as the country and 'States 303824646' as the population." },
      { q: "For input lines like \"United States 303824646\", is this approach valid?\nFind the LAST space at position i, then extract `line.substring(0, i).trim()` and `line.substring(i)`.", choices: ["Valid","Not valid"], answer: 1, code: "// Approach: split on LAST space, use substring(i) for population\nint i = line.lastIndexOf(' ');\nString country = line.substring(0, i).trim();  // \"United States\"\nString pop     = line.substring(i);            // \" 303824646\" ← leading space!\n// Integer.parseInt(\" 303824646\") throws NumberFormatException", explanation: "substring(i) includes the space before the number, giving ' 303824646'. Parsing that string as an integer fails — you need substring(i + 1) to skip the space." },
      { q: "For input lines like \"United States 303824646\", is this approach valid?\nFind the LAST space at position i, then extract `line.substring(0, i).trim()` and `line.substring(i + 1)`.", choices: ["Valid","Not valid"], answer: 0, code: "// Approach: split on LAST space, use substring(i+1) for population\nint i = line.lastIndexOf(' ');\nString country = line.substring(0, i).trim();  // \"United States\" ✓\nString pop     = line.substring(i + 1);        // \"303824646\"    ✓", explanation: "substring(i + 1) skips the space to get just '303824646'. Using lastIndexOf correctly handles multi-word country names like 'United States'." },
      { q: "For parsing country names and populations, is this approach valid?\nAppend results of `in.next()` (with space separators) while `in.hasNextInt()` is false. Then call `in.nextInt()` to read population.", choices: ["Valid","Not valid"], answer: 0, code: "// Reads words until encountering an integer → handles multi-word names\n// Works for: \"United States 303824646\"", explanation: "Read tokens with next() until hasNextInt() is true — all those words form the country name. Then nextInt() gets the population. Works for any number of words!" },
      { q: "When the pending input starts with line \"2 United States\",\n`in.nextInt()` yields 2, and `in.next()` yields \"United\".", choices: ["True","False"], answer: 0, code: "// nextInt() reads 2, positions scanner after \"2\"\n// next() reads next token: \"United\" ✓", explanation: "nextInt() grabs 2, then next() reads the next whitespace-separated token: 'United'. That's correct." },
      { q: "When the pending input starts with line \"2 United States\",\n`in.nextInt()` yields 2, and `in.nextLine()` yields \"United States\".", choices: ["True","False"], answer: 1, code: "// After nextInt() reads \"2\", remaining on line: \" United States\"\n// nextLine() returns \" United States\" (with leading space), not \"United States\"", explanation: "After nextInt() reads '2', the remaining text on that line is ' United States' (with a leading space). nextLine() returns that — not just 'United States'." },
      { q: "When the pending input is:\n2\nUnited States\n(two separate lines)\n`in.nextInt()` yields 2, and `in.nextLine()` yields \"United States\".", choices: ["True","False"], answer: 1, code: "// nextInt() reads 2, buffer has \"\\n\"\n// nextLine() reads \"\" (empty — rest of line 1)\n// Need ANOTHER nextLine() to get \"United States\"", explanation: "nextInt() reads 2, but the newline after '2' stays in the buffer. nextLine() reads that leftover newline (empty string), not 'United States'. You need a second nextLine()." },
      { q: "You should never mix `nextInt`/`nextDouble` and `nextLine` in the same program.", choices: ["True","False"], answer: 1, code: "", explanation: "You CAN mix them! You just need to call an extra nextLine() to consume the leftover newline character left by nextInt() or nextDouble()." },
      { q: "If you call `nextInt`/`nextDouble` to read the number on a line, and then want to read the next line as a string with `nextLine`, add another call to `nextLine` (to consume the newline).", choices: ["True","False"], answer: 0, code: "int value = in.nextInt();\nin.nextLine(); // consume the '\\n' left by nextInt\nString line = in.nextLine(); // now reads next line ✓", explanation: "After nextInt(), call nextLine() once to swallow the leftover newline, then call nextLine() again to actually read the next line." },
      { q: "You can avoid the `nextInt`/`nextLine` pitfall by reading all lines with `nextLine`, and then processing each line.", choices: ["True","False"], answer: 0, code: "", explanation: "Reading everything with nextLine() avoids the mixing pitfall entirely. Parse numbers from each line string yourself afterward." },
    ]
  },
  {
    section: "Section 46.8",
    description: "Command-line arguments — how args[] is populated, args.length, and accessing specific argument values by index.",
    title: "Section 46.8 — Command-Line Arguments",
    questions: [
      { q: "Assume a program is executed as shown:\n`java MyClass -v8 -h data.txt output.txt`\nWhat is the value of `args.length`?", choices: ["2","4","5","6","3"], answer: 1, code: "// args: [\"-v8\", \"-h\", \"data.txt\", \"output.txt\"]\n// args.length = 4", explanation: "The command has 4 arguments: -v8, -h, data.txt, output.txt. The program name 'MyClass' is NOT in args[]. So args.length = 4." },
      { q: "Select the output produced, assuming the program is executed as:\n`java Question -h datafile.txt results.txt`", choices: ["datafile.txt results.txt","-h datafile.txt","Question -h","Execution would result in a run-time index-out-of-bounds error","-h"], answer: 0, code: "public class Question {\n    public static void main(String[] args) {\n        System.out.println(args[1] + \" \" + args[2]);\n    }\n}\n// args[0]=\"-h\", args[1]=\"datafile.txt\", args[2]=\"results.txt\"", explanation: "args[0] = '-h', args[1] = 'datafile.txt', args[2] = 'results.txt'. So args[1] + ' ' + args[2] prints 'datafile.txt results.txt'." },
    ]
  },
];
